name: Publish qwc-demo-db docker image

on: [push, workflow_dispatch]

jobs:

    build:
      runs-on: ubuntu-latest
      if: github.event_name == 'push'
      steps:

      - uses: actions/checkout@master

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Get version tag
        id: get_tag
        run: |
          if [ ${{ startsWith(github.ref, 'refs/tags/') }} = true ]; then
            echo ::set-output name=tag::latest,${GITHUB_REF:10}
          else
            echo ::set-output name=tag::latest
          fi

      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@2.18
        with:
          name: neotrade-ts/${{ github.event.repository.name }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          tags: "${{ steps.get_tag.outputs.tag }}"
          platforms: linux/arm64,linux/amd64
